allowBuilds:
  esbuild: true
  unrs-resolver: true
overrides:
  '@babel/core': 7.29.7
  'brace-expansion@^1.1.0': 1.1.16
  'brace-expansion@^2.0.0': 2.1.2
  electron-to-chromium: 1.5.368
  fast-uri: 3.1.4
  js-yaml: 3.15.0
  qs: 6.15.2
  tmp: 0.2.7
  tsup>esbuild: 0.28.1
  vitepress>vite: 6.4.3
packageExtensions:
  vite@6.4.3:
    dependencies:
      esbuild: 0.25.12
